# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # TODO: Move these to an alternate configuration file that can be imported.
    mannequin.extensions:
        htmldiscovery:
            extension: 'html'
            directories:
                - '/Users/jeff/Sites/mannequin/src/Html/demo/'
            pattern: '*.html'
            root: '/Users/jeff/Sites/mannequin/src/Html/demo/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $chainDiscovery: '@LastCall\Mannequin\Core\Discovery\ChainDiscovery'
            $mannequinExtensionConfig: '%mannequin.extensions%'
            $pathPackage: 'Symfony\Component\Asset\PathPackage'
            $expressionLanguage: 'Symfony\Component\ExpressionLanguage\ExpressionLanguage'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

#    LastCall\Mannequin\Core\Console\Command\DebugCommand:

    LastCall\Mannequin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    LastCall\Mannequin\Core\Discovery\ChainDiscovery:
        configurator: [ '@LastCall\Mannequin\Core\Discovery\ChainDiscoveryConfigurator', 'configure']


#    # controllers are imported separately to make sure services can be injected
#    # as action arguments even if you don't extend any base controller class
#    App\Controller\:
#        resource: '../src/Controller/'
#        tags: ['controller.service_arguments']
#
#    # add more service definitions when explicit configuration is needed
#    # please note that last definitions always *replace* previous ones
